name: MSVC-CI
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A Win32 ..
          cmake --build . --config Debug
          cmake --build . --config Release
          
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create Output Folder
        run: mkdir output

      - name: Copy Build to Output
        run: cp -r build/* output/

      - name: Commit and Push Changes
        run: |
          git add output/*
          git commit -m "Update output from build"
          git push

      # This should probably be fixed to work from MSVC without needing to
      # use a bash shell and the GNU userland tools...  But for now, the
      # GH Actions environment provides what we need.
      - name: Test
        run: |
          cd build\Debug
          bash.exe ..\..\tests\all_tests.sh
        env:
          PYTHON_EXE: python.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pycdc-release
          path: build\Release\*.exe
